version: 2

models:
  - name: crm_quote
    description: "Les quotes"
    comment: "AHO 202506: test création vue DBT"
    columns:
      - name: deal_id
        description: "Identifiant du deal"
      - name: quote_id
        description: "Identifiant du devis"
      - name: account_id
        description: "Identifiant du compte"
      - name: _75MGRTECH
        description: "Champ technique MGR"
      - name: ACTUALISATIONOFMGRUNTILSTARTINGDATE
        description: "Actualisation du MGR jusqu'à la date de début"
      - name: CAPONINDEXATIONOFMGR
        description: "Plafond sur l'indexation du MGR"
