
version: 2

models:
  - name: CRM_DEAL_QUOTE_RELEVANT
    description: "les deal_quote pour chaque step"
    comment: "SGE 202506: most sifgnificant view for each step of the deal for PBI"
    columns:
      - name: opportunityid
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
